events { worker_connections 1024; }

http {
    upstream ml_cluster {
        # This tells Nginx to look for our 'api' containers on port 8000
        server api:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ml_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}